### ISSUE TITLE
6.1 As a museum director I want to be able to change the pictures on the museum's homepage so that I can keep the homepage interesting and up to date

### ISSUE THREAD

**Issue by claytonmanchac** [RebeccaEKuhlman/museum-tours#1]
Relative size: 5

Given a director is logged in, when they are on the homepage, then they should see an edit button under the image banner where they can upload a new image to show on the homepage

Given either an unregistered user or a logged in user is viewing the homepage they should see the latest image uploaded by the director

**Comment by blake-gebhardt** [comment]
Museum director nerfed
