### ISSUE TITLE
6.5 As a museum director I want to be able to view the homepage as a user so that I can make sure my updates look good

### ISSUE THREAD

**Issue by claytonmanchac** [RebeccaEKuhlman/museum-tours#14]
Relative size: 1

Given a director is logged in, when they are viewing the homepage, then they should see a button that changes the view to make the screen look like a user

Given a director is logged in, when they are viewing the homepage as a user, then they should see a button that changes the view back to director edit mode

**Comment by TrevorDohm** [comment]
This is by design - A Museum Director clicks a button to show their command page. This is on the profile page.
