### ISSUE TITLE
4.1 As a user I want to be able to upload photos for a tour so that other users can see the real experience

### ISSUE THREAD

**Issue by blake-gebhardt** [RebeccaEKuhlman/museum-tours#2]
3
Given a user wants to upload a photo, when the user clicks on the upload photo button, the user should be prompted for or permission to access the library.
Given the user is presented with the permission popup, when the user clicks allow, the user should be able to see images in the library to choose from
Given the user is presented with the permission popup, when the user clicks deny, the user should be redirected back to the profile page

**Comment by TrevorDohm** [comment]
Discussed with the product team - we will not have upload functionality on the website.
