### ISSUE TITLE
2.5 As a user I want to be able to be notified about the tours I have booked so that I can receive updates about the booked tour.

### ISSUE THREAD

**Issue by agenato** [RebeccaEKuhlman/museum-tours#23]
Sizing: 3
Given a user wants to be notified about the tour, when they booking the tour, then they can select the notify button.
Given a user wants to be notified about the tour, when they booking the tour, then they can select the notify button.

**Comment by blake-gebhardt** [comment]
Users will see their upcoming tours on profile page.
