### ISSUE TITLE
5.3 As a user, I want to toggle between related upcoming exhibits/tours so that i may be able to find other experiences i might enjoy

### ISSUE THREAD

**Issue by claytonmanchac** [RebeccaEKuhlman/museum-tours#26]
Relative size: 8

Given a user is scrolling through the events when a user clicks on an event icon and scrolls to the bottom of the page past details and information and descriptions and reviews etc, there should be related events 

Given a user is viewing the information and descriptions of a specific event when a user clicks on a related event at the bottom of the page, they should be allowed to return to the previous event page if they press back

**Comment by blake-gebhardt** [comment]
sorting and filtering scrapped
