### ISSUE TITLE
7.5 As a registered user, I want to be able to add an affiliation with a museum which allows me to act like a museum director so that I can take advantage of the benefits of a museum director account

### ISSUE THREAD

**Issue by agenato** [RebeccaEKuhlman/museum-tours#29]
Sizing: 13
Given a museum director needs access to editing the events on behalf their museum, when they requests affiliation with their museum, their affiliation is verified.
Given a director is logged in, when a user tries to affiliate with their museum, then they should be able to see that and either accept or deny the request

**Comment by TrevorDohm** [comment]
Discussed with Product Team - We have two different types of accounts, user and museum director. A user cannot add an affiliation, but a museum director can add another user. Have not added this yet.

**Comment by EileenG02** [comment]
Dropping issue. The whole chicken/egg situation about which comes first, the user or director was too complicated for our project scope.
