### ISSUE TITLE
5.5 As a user, I want to be able to filter by the type of experience which I am taking part in so that i may easier find experiences with topics i will enjoy

### ISSUE THREAD

**Issue by claytonmanchac** [RebeccaEKuhlman/museum-tours#31]
Relative Size: 3

Given that a user has a specific interest, then they are able to filter options to that they want

Given that a user wants to filter out certain tours, then they will be able to remove the disliked tours from the viewing gallery

**Comment by blake-gebhardt** [comment]
filtering scrapped
