### ISSUE TITLE
3.8 As a museum director, I want to have a confirmation message before editing, adding, or removing a tour so that if the tour is being altered in anyway , I am given a prompt to confirm

### ISSUE THREAD

**Issue by EileenG02** [RebeccaEKuhlman/museum-tours#43]
Relative size: 2
- Given that the museum director made a mistake making their tour, then they are able to select no and not edit their slot
- Given that the museum director wants to confirm their tour, then they are able to select yes and confirm the edit to their slot

**Comment by blake-gebhardt** [comment]
Museum director nerfed
