### ISSUE TITLE
3.5 - As a museum director I want to be able to remove tour slots so that if any guest plans to cancel their tour I can remove it

### ISSUE THREAD

**Issue by RebeccaEKuhlman** [RebeccaEKuhlman/museum-tours#44]
Size: 3
Given that the museum director needs to cancel a tour, then they are able to delete those tours from the site 
Given that a user is viewing a deleted tour, then they will be notified it has been removed

**Comment by TrevorDohm** [comment]
This is not done

**Comment by blake-gebhardt** [comment]
Museum director nerfed
