### ISSUE TITLE
6.2 As a museum director I want to be able to update the "What's New" section of the homepage so that site visitors know new and exciting exhibits at the museum

### ISSUE THREAD

**Issue by claytonmanchac** [RebeccaEKuhlman/museum-tours#6]
relative size: 8

Given a director is logged in, when viewing the homepage, then they should see an edit button that allows them to edit the "What's New" section

Given either an unregistered user or a logged in user is viewing the homepage they should see the most up to date description

**Comment by blake-gebhardt** [comment]
Museum director nerfed
