### ISSUE TITLE
6.3 As a museum director I want to be able to add tours to the homepage so that users have quick access to the tours page as well as information about  the latest tours offered by the museum

### ISSUE THREAD

**Issue by claytonmanchac** [RebeccaEKuhlman/museum-tours#9]
Relative Size: 5

Given an unregistered user or a logged in user is viewing the homepage, when they click on the tour, then it should take them to the tour page to provide more information

Given a user is logged in as a director, when they are on the homepage, then they should be able to create a link to a tour and add it to the homepage

**Comment by blake-gebhardt** [comment]
Museum director nerfed
